import type { Config } from '@react-router/dev/config'
import { copyFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { listCaseStudies, shouldIncludeDrafts } from './scripts/case-studies.ts'
import { tourPaths, tourRedirects } from './src/data/tour.manifest'
import { SITE } from './src/site'

// Prerender runs in production mode; drafts are included only for preview builds.
const caseStudies = listCaseStudies({
  includeDrafts: shouldIncludeDrafts('production'),
})
const workPages = caseStudies.length
  ? ['/work', ...caseStudies.map((study) => `/work/${study.slug}`)]
  : []

const pages = [
  '/',
  '/resume',
  ...workPages,
  '/lab',
  '/lab/tape',
  '/system',
  ...tourPaths(),
]

// Static prerendering (ADR 0001): every page is an HTML file with its content
// in it. Netlify serves those files directly; anything else gets 404.html with
// a real 404 status (ADR 0003).
export default {
  appDirectory: 'src',
  buildDirectory: 'build',
  ssr: false,
  prerender: [...pages, '/404'],
  async buildEnd({ reactRouterConfig }) {
    const client = path.join(reactRouterConfig.buildDirectory, 'client')
    await copyFile(
      path.join(client, '404', 'index.html'),
      path.join(client, '404.html')
    )
    const redirects = tourRedirects()
      .map(([from, to, status]) => `${from}  ${to}  ${status}`)
      .join('\n')
    await writeFile(
      path.join(client, '_redirects'),
      `# Generated by react-router.config.ts from src/data/tour.manifest.ts\n${redirects}\n`
    )
    const urls = pages
      .map((page) => `  <url><loc>${new URL(page, SITE.url)}</loc></url>`)
      .join('\n')
    await writeFile(
      path.join(client, 'sitemap.xml'),
      `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`
    )
    await writeFile(
      path.join(client, 'robots.txt'),
      `User-agent: *\nAllow: /\n\nSitemap: ${new URL('/sitemap.xml', SITE.url)}\n`
    )
  },
} satisfies Config
