// Writes src/styles/tokens.generated.css from the TypeScript token source.
// `--check` fails (for CI) when the committed file is out of date.
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { tokensStylesheet } from '../src/tokens/css.ts'
import { semanticColors } from '../src/tokens/semantic.ts'

const outputs = [
  {
    file: path.resolve(
      import.meta.dirname,
      '../src/styles/tokens.generated.css'
    ),
    content: tokensStylesheet(),
  },
  {
    // Resolved constants for code that only needs a value (e.g. the
    // theme-color meta tag), so the resolver doesn't ship on every page.
    file: path.resolve(import.meta.dirname, '../src/tokens/generated.ts'),
    content: [
      '// GENERATED by scripts/build-tokens.ts from src/tokens/. Do not edit.',
      `export const RESOLVED = ${JSON.stringify(
        { light: semanticColors('light'), dark: semanticColors('dark') },
        null,
        2
      )} as const`,
      '',
    ].join('\n'),
  },
]

const check = process.argv.includes('--check')
let stale = false
for (const { file, content } of outputs) {
  const name = path.relative(process.cwd(), file)
  if (check) {
    let current = ''
    try {
      current = readFileSync(file, 'utf8')
    } catch {
      // missing counts as stale
    }
    if (current !== content) {
      console.error(`✘ ${name} is out of date. Run: yarn tokens`)
      stale = true
    }
  } else {
    writeFileSync(file, content)
    console.log(`Tokens → ${name}`)
  }
}
if (check) {
  if (stale) process.exit(1)
  console.log('✔ Generated token files match src/tokens/')
}
