import { type Mode } from './accent.ts'
import { withAlpha } from './oklch.ts'
import { data, duration, easing, font, radius, space } from './reference.ts'
import { type SemanticColors, semanticColors } from './semantic.ts'
import { themes } from './themes.ts'

/** Semantic token → CSS custom property name (kebab-case). */
export const cssVar = (token: string) =>
  `--${token.replace(/[A-Z]/g, (char) => `-${char.toLowerCase()}`)}`

/** Tier 3, component tokens, derived from the semantic tier. */
export const componentTokens = (colors: SemanticColors, mode: Mode) => ({
  buttonBg: colors.accent,
  buttonFg: colors.onAccent,
  buttonBgHover: colors.accentStrong,
  carouselDotActive: colors.accent,
  focusRing: colors.focus,
  flashUp: withAlpha(colors.positive, mode === 'light' ? 0.16 : 0.18),
  flashDown: withAlpha(colors.negative, mode === 'light' ? 0.16 : 0.18),
  danger: colors.negative,
})

/**
 * Declarations for one mode with the given accent. Used for the generated
 * stylesheet and at runtime, when the tour applies a visitor's color.
 */
export const colorDeclarations = (mode: Mode, accentInput?: string) => {
  const colors = semanticColors(mode, accentInput)
  const all = { ...colors, ...componentTokens(colors, mode) }
  return Object.entries(all).map(
    ([token, value]) => `  ${cssVar(token)}: ${value};`
  )
}

/** Accent-only declarations, for the runtime override in the tour. */
export const accentDeclarations = (mode: Mode, accentInput: string) => {
  const keys = [
    'accent',
    'accentStrong',
    'onAccent',
    'accentSubtle',
    'focus',
    'buttonBg',
    'buttonFg',
    'buttonBgHover',
    'carouselDotActive',
    'focusRing',
  ]
  return colorDeclarations(mode, accentInput).filter((line) =>
    keys.some((key) => line.startsWith(`  ${cssVar(key)}:`))
  )
}

const semanticNames = Object.keys(semanticColors('light'))

/** The full generated stylesheet (scripts/build-tokens.ts writes it). */
export const tokensStylesheet = () => {
  const scale = (prefix: string, values: Record<string, string>) =>
    Object.entries(values).map(
      ([key, value]) => `  --${prefix}-${key}: ${value};`
    )
  const themeBlocks = Object.values(themes).map(
    (theme) =>
      `:root[data-theme='${theme.name}'] {\n  --font-body: ${theme.font.body};\n  --font-display: ${theme.font.display};\n  --radius-theme: ${theme.radius};\n  --motion-scale: ${theme.motion};\n}`
  )
  const componentNames = Object.keys(
    componentTokens(semanticColors('light'), 'light')
  )
  const themeColorUtilities = [...semanticNames, ...componentNames].map(
    (token) => `  --color${cssVar(token).slice(1)}: var(${cssVar(token)});`
  )
  return [
    '/* GENERATED by scripts/build-tokens.ts from src/tokens/. Do not edit. */',
    '',
    ':root {',
    ...colorDeclarations('light'),
    ...scale('space', space),
    ...scale('radius', radius),
    ...scale('duration', duration),
    ...scale('easing', easing),
    `  --font-body: ${font.system};`,
    `  --font-display: ${font.system};`,
    `  --font-mono: ${font.mono};`,
    `  --radius-theme: ${radius.md};`,
    '  --motion-scale: 1;',
    ...Object.entries(data).map(
      ([name, value]) => `  --data-${name}: ${value};`
    ),
    '  color-scheme: light;',
    '}',
    '',
    // Mode follows MUI's color-scheme class on <html>, set before paint.
    ':root.dark {',
    ...colorDeclarations('dark'),
    '  color-scheme: dark;',
    '}',
    '',
    ...themeBlocks,
    '',
    // Tailwind reads the same variables (ADR 0002).
    '@theme inline {',
    ...themeColorUtilities,
    '}',
    '',
    '@custom-variant dark (&:where(.dark, .dark *));',
    '',
    '/* Motion follows the site setting (src/motion/motion.ts), which already',
    '   folds in prefers-reduced-motion, so these replace the media-query variants. */',
    "@custom-variant motion-reduce (&:where([data-motion='reduce'], [data-motion='reduce'] *));",
    "@custom-variant motion-safe (&:where([data-motion='full'], [data-motion='full'] *));",
    '',
  ].join('\n')
}
