// GENERATED by scripts/build-tokens.ts from src/tokens/. Do not edit.
export const RESOLVED = {
  "light": {
    "canvas": "#f6f7f9",
    "surface": "#ffffff",
    "surfaceOverlay": "rgba(255, 255, 255, 0.8)",
    "backdrop": "#dcdde0",
    "fg": "#15181e",
    "fgMuted": "#4a505c",
    "border": "#d5d9e0",
    "accent": "#246ddf",
    "accentStrong": "#0757c8",
    "onAccent": "#ffffff",
    "accentSubtle": "#e0ecff",
    "focus": "#246ddf",
    "positive": "#0f7a3a",
    "negative": "#c0262d",
    "shadow": "rgba(0, 0, 0, 0.25)",
    "highlight": "rgba(255, 255, 255, 0.75)"
  },
  "dark": {
    "canvas": "#0e1116",
    "surface": "#171b22",
    "surfaceOverlay": "rgba(0, 0, 0, 0.72)",
    "backdrop": "#111213",
    "fg": "#e7eaef",
    "fgMuted": "#a6adb9",
    "border": "#2b313c",
    "accent": "#6ca4ff",
    "accentStrong": "#92bcff",
    "onAccent": "#0e1116",
    "accentSubtle": "#1d293d",
    "focus": "#6ca4ff",
    "positive": "#4ade80",
    "negative": "#f87171",
    "shadow": "rgba(0, 0, 0, 0.5)",
    "highlight": "rgba(255, 255, 255, 0.25)"
  }
} as const
